version: "3"

volumes:
  code-server-config:

networks:
  nginxproxymanager_backend:
    external: true
    
services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PASSWORD=replace-with-secure-password # optional
      - HASHED_PASSWORD= # optional
      - SUDO_PASSWORD=replace-with-secure-password # optional
      - SUDO_PASSWORD_HASH= # optional
      - PROXY_DOMAIN=code-server.my.domain
      - DEFAULT_WORKSPACE=/config/workspace
    volumes:
      - code-server-config:/config
    ports:
      - 8443:8443
    restart: unless-stopped
    networks:
      - nginxproxymanager_backend
